# Generated by Django 4.2 on 2023-04-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
